export default {
  page: 1,
  results: [
    {
      original_name: "The Umbrella Academy",
      id: 75006,
      name: "The Umbrella Academy",
      vote_count: 967,
      vote_average: 8.4,
      first_air_date: "2019-02-15",
      poster_path: "/scZlQQYnDVlnpxFTxaIv2g0BWnL.jpg",
      genre_ids: [35, 18, 10759, 10765],
      original_language: "en",
      backdrop_path: "/qJxzjUjCpTPvDHldNnlbRC4OqEh.jpg",
      overview:
        "A dysfunctional family of superheroes comes together to solve the mystery of their father's death, the threat of the apocalypse and more.",
      origin_country: ["US"],
      popularity: 145.097,
      media_type: "tv",
    },
    {
      original_name: "The Rain",
      id: 76719,
      name: "The Rain",
      vote_count: 220,
      vote_average: 7.1,
      first_air_date: "2018-05-04",
      poster_path: "/bBBpi5pgOEZlCOgx2q116oPdJnx.jpg",
      genre_ids: [18, 10765],
      original_language: "da",
      backdrop_path: "/rfK7BGBUoqXc2EiKGbKuzaeSDjW.jpg",
      overview:
        "After a brutal virus wipes out most of the population, two young siblings embark on a perilous search for safety. A Scandinavian thriller series.",
      origin_country: ["DK"],
      popularity: 80.199,
      media_type: "tv",
    },
    {
      backdrop_path: "/uzUPwWSAheYKdavFCcod9M6y2rf.jpg",
      first_air_date: "2020-07-16",
      genre_ids: [10759, 10765],
      id: 83125,
      name: "Cursed",
      origin_country: ["GB"],
      original_language: "en",
      original_name: "Cursed",
      overview:
        "In this fresh take on the Arthurian legend, teenager Nimue joins forces with mercenary Arthur on a quest to find Merlin and deliver an ancient sword.",
      poster_path: "/wrLC5kx0nEq9U0MyJD7dnOT6m5F.jpg",
      vote_average: 7.4,
      vote_count: 365,
      popularity: 35.69,
      media_type: "tv",
    },
    {
      original_name: "The 100",
      id: 48866,
      name: "The 100",
      vote_count: 3787,
      vote_average: 7.6,
      first_air_date: "2014-03-19",
      poster_path: "/wcaDIAG1QdXQLRaj4vC1EFdBT2.jpg",
      genre_ids: [18, 10759, 10765],
      original_language: "en",
      backdrop_path: "/hTExot1sfn7dHZjGrk0Aiwpntxt.jpg",
      overview:
        "100 years in the future, when the Earth has been abandoned due to radioactivity, the last surviving humans live on an ark orbiting the planet — but the ark won't last forever. So the repressive regime picks 100 expendable juvenile delinquents to send down to Earth to see if the planet is still habitable.",
      origin_country: ["US"],
      popularity: 104.165,
      media_type: "tv",
    },
    {
      original_name: "Game of Thrones",
      id: 1399,
      name: "Game of Thrones",
      vote_count: 9640,
      vote_average: 8.3,
      first_air_date: "2011-04-17",
      poster_path: "/u3bZgnGQ9T01sWNhyveQz0wH0Hl.jpg",
      genre_ids: [18, 10765],
      original_language: "en",
      backdrop_path: "/suopoADq0k8YZr4dQXcU6pToj6s.jpg",
      overview:
        "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
      origin_country: ["US"],
      popularity: 119.519,
      media_type: "tv",
    },
    {
      original_name: "La casa de papel",
      id: 71446,
      name: "Money Heist",
      vote_count: 8398,
      vote_average: 8.4,
      first_air_date: "2017-05-02",
      poster_path: "/MoEKaPFHABtA1xKoOteirGaHl1.jpg",
      genre_ids: [80, 18],
      original_language: "es",
      backdrop_path: "/xGexTKCJDkl12dTW4YCBDXWb1AD.jpg",
      overview:
        "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose. Five months of seclusion - memorizing every step, every detail, every probability - culminate in eleven days locked up in the National Coinage and Stamp Factory of Spain, surrounded by police forces and with dozens of hostages in their power, to find out whether their suicide wager will lead to everything or nothing.",
      origin_country: ["ES"],
      popularity: 46.134,
      media_type: "tv",
    },
    {
      original_name: "Dark",
      id: 70523,
      name: "Dark",
      vote_count: 3016,
      vote_average: 8.5,
      first_air_date: "2017-12-01",
      poster_path: "/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
      genre_ids: [80, 18, 9648, 10765],
      original_language: "de",
      backdrop_path: "/3lBDg3i6nn5R2NKFCJ6oKyUo2j5.jpg",
      overview:
        "A missing child causes four families to help each other for answers. What they could not imagine is that this mystery would be connected to innumerable other secrets of the small town.",
      origin_country: ["DE"],
      popularity: 71.525,
      media_type: "tv",
    },
    {
      original_name: "Stargirl",
      id: 80986,
      name: "Stargirl",
      vote_count: 500,
      vote_average: 8.0,
      first_air_date: "2020-05-18",
      poster_path: "/sWSGc3Bb7aCTOPvAIkkhqI7ae9H.jpg",
      genre_ids: [80, 18, 10759, 10765],
      original_language: "en",
      backdrop_path: "/b5lKppEquuQWm6fTjGcu2g8FJgs.jpg",
      overview:
        'Courtney Whitmore, a smart, athletic and above all else kind girl, discovers her step-father has a secret: he used to be the sidekick to a superhero. "Borrowing" the long-lost hero’s cosmic staff, she becomes the unlikely inspiration for an entirely new generation of superheroes.',
      origin_country: ["US"],
      popularity: 48.336,
      media_type: "tv",
    },
    {
      original_name: "Wizards: Tales of Arcadia",
      id: 105797,
      name: "Wizards: Tales of Arcadia",
      vote_count: 7,
      vote_average: 8.4,
      first_air_date: "2020-08-07",
      poster_path: "/aAMcPNLzCML40q7qmuB0jrZIcsI.jpg",
      genre_ids: [16],
      original_language: "en",
      backdrop_path: "/oTFDGizS4kszfUOG9uBqsIfG3sN.jpg",
      overview:
        "Merlin’s apprentice joins Arcadia’s heroes on a time-bending adventure in Camelot, where conflict is brewing between the human, troll and magical worlds.",
      origin_country: ["US"],
      popularity: 49.474,
      media_type: "tv",
    },
    {
      original_name: "Perry Mason",
      id: 85853,
      name: "Perry Mason",
      vote_count: 92,
      vote_average: 7.4,
      first_air_date: "2020-06-21",
      poster_path: "/gPBf35AqvXHvKEpDHaQ4D9xXxeX.jpg",
      genre_ids: [80, 18, 9648],
      original_language: "en",
      backdrop_path: "/jGwCKq2EbQbsgNTBM2NoEzFHRdh.jpg",
      overview:
        "Set in 1932 Los Angeles, the series focuses on the origin story of famed defense lawyer Perry Mason. Living check-to-check as a low-rent private investigator, Mason is haunted by his wartime experiences in France and suffering the effects of a broken marriage. L.A. is booming while the rest of the country recovers from the Great Depression — but a kidnapping gone very wrong leads to Mason exposing a fractured city as he uncovers the truth of the crime.",
      origin_country: ["US"],
      popularity: 34.533,
      media_type: "tv",
    },
    {
      original_name: "Marvel's Agents of S.H.I.E.L.D.",
      id: 1403,
      name: "Marvel's Agents of S.H.I.E.L.D.",
      vote_count: 1940,
      vote_average: 7.2,
      first_air_date: "2013-09-24",
      poster_path: "/gHUCCMy1vvj58tzE3dZqeC9SXus.jpg",
      genre_ids: [18, 10759, 10765],
      original_language: "en",
      backdrop_path: "/mUCV0W6TaAk8UWA5yAmqCywC63F.jpg",
      overview:
        "Agent Phil Coulson of S.H.I.E.L.D. (Strategic Homeland Intervention, Enforcement and Logistics Division) puts together a team of agents to investigate the new, the strange and the unknown around the globe, protecting the ordinary from the extraordinary.",
      origin_country: ["US"],
      popularity: 101.69,
      media_type: "tv",
    },
    {
      original_name: "Doom Patrol",
      id: 79501,
      name: "Doom Patrol",
      vote_count: 581,
      vote_average: 7.4,
      first_air_date: "2019-02-15",
      poster_path: "/drlfSCIlMKrEeMPhi8pqY4xGxj.jpg",
      genre_ids: [10759, 10765],
      original_language: "en",
      backdrop_path: "/rqHL4HsLCix9H6vhCwAuSOge0NS.jpg",
      overview:
        "The Doom Patrol’s members each suffered horrible accidents that gave them superhuman abilities — but also left them scarred and disfigured. Traumatized and downtrodden, the team found purpose through The Chief, who brought them together to investigate the weirdest phenomena in existence — and to protect Earth from what they find.",
      origin_country: ["US"],
      popularity: 46.974,
      media_type: "tv",
    },
    {
      original_name: "Yellowstone",
      id: 73586,
      name: "Yellowstone",
      vote_count: 121,
      vote_average: 7.7,
      first_air_date: "2018-06-20",
      poster_path: "/43nVQqVsrshaOx9GfJq6JstsfCX.jpg",
      genre_ids: [18, 37],
      original_language: "en",
      backdrop_path: "/oBilGalyrQJTtDuYIljRQGNXXb8.jpg",
      overview:
        "Follow the violent world of the Dutton family, who controls the largest contiguous ranch in the United States. Led by their patriarch John Dutton, the family defends their property against constant attack by land developers, an Indian reservation, and America’s first National Park.",
      origin_country: ["US"],
      popularity: 50.75,
      media_type: "tv",
    },
    {
      original_name: "사이코지만 괜찮아",
      id: 96462,
      name: "It's Okay to Not Be Okay",
      vote_count: 12,
      vote_average: 9.4,
      first_air_date: "2020-06-20",
      poster_path: "/vBaLz8kZNXYvTjHwrTewkTw3l7k.jpg",
      genre_ids: [35, 18],
      original_language: "ko",
      backdrop_path: "/qOQFBEbNqDu7tmfL9wKMc8ECW3L.jpg",
      overview:
        "Desperate to escape from his emotional baggage and the heavy responsibility he’s had all his life, a psychiatric ward worker begins to heal with help from the unexpected—a woman who writes fairy tales but doesn’t believe in them.",
      origin_country: ["KR"],
      popularity: 29.694,
      media_type: "tv",
    },
    {
      original_name: "Transformers: War for Cybertron",
      id: 100617,
      name: "Transformers: War for Cybertron",
      vote_count: 13,
      vote_average: 8.2,
      first_air_date: "2020-07-30",
      poster_path: "/oKdVrAhEcxJ0jqNI74RNMdf9WUF.jpg",
      genre_ids: [16, 10759, 10762, 10765],
      original_language: "en",
      backdrop_path: "/bxZrG6wsmKMoUC1q4ByTWDRHaOh.jpg",
      overview:
        "On their dying planet, the Autobots and Decepticons battle fiercely for control of the AllSpark in the Transformers universe's origin story.",
      origin_country: ["US"],
      popularity: 16.053,
      media_type: "tv",
    },
    {
      original_name: "The Alienist",
      id: 71769,
      name: "The Alienist",
      vote_count: 180,
      vote_average: 7.6,
      first_air_date: "2018-01-22",
      poster_path: "/1qzuS7b2XjiVcWwmDkOyE5hIxUM.jpg",
      genre_ids: [80, 18, 9648],
      original_language: "en",
      backdrop_path: "/yVPGTGE98yO9rCI3TUTFIsxf4eh.jpg",
      overview:
        "New York, 1896. Police commissioner Theodore Roosevelt brings together criminal psychologist Dr. Laszlo Kreizler, newspaper illustrator John Moore and secretary Sara Howard to investigate several murders of male prostitutes.",
      origin_country: ["US"],
      popularity: 36.178,
      media_type: "tv",
    },
    {
      original_name: "Star Trek: Lower Decks",
      id: 85948,
      name: "Star Trek: Lower Decks",
      vote_count: 9,
      vote_average: 5.4,
      first_air_date: "2020-08-06",
      poster_path: "/i7Em3r7KCyNfkOwMkyqN8UMvK8S.jpg",
      genre_ids: [16, 35, 10759, 10765],
      original_language: "en",
      backdrop_path: "/kG7GwGBHpCI6lA6SaEydKHHOxkU.jpg",
      overview:
        "The lives of the support crew serving on one of Starfleet's least important ships, the U.S.S. Cerritos, in 2380. Ensigns Mariner, Boimler, Rutherford and Tendi have to keep up with their duties and their social lives, often while the ship is being rocked by a multitude of sci-fi anomalies.",
      origin_country: ["US"],
      popularity: 30.928,
      media_type: "tv",
    },
    {
      original_name: "Wynonna Earp",
      id: 65988,
      name: "Wynonna Earp",
      vote_count: 331,
      vote_average: 7.6,
      first_air_date: "2016-04-01",
      poster_path: "/qnIaDelA81dmFaXrhpz6M6dpGSD.jpg",
      genre_ids: [37, 10759, 10765],
      original_language: "en",
      backdrop_path: "/qVu5MC7DiDOrlcKNZsb9rEJJ1UI.jpg",
      overview:
        "Wyatt Earp's great granddaughter Wynonna battles demons and other creatures with her unique abilities and a posse of dysfunctional allies - the only thing that can bring the paranormal to justice.",
      origin_country: ["CA", "US"],
      popularity: 49.131,
      media_type: "tv",
    },
    {
      original_name: "The New Legends of Monkey",
      id: 71577,
      name: "The New Legends of Monkey",
      vote_count: 21,
      vote_average: 7.3,
      first_air_date: "2018-01-28",
      poster_path: "/jwu04xIT0kNV9ZpVZ6wNBGPr0eG.jpg",
      genre_ids: [35, 10759, 10765],
      original_language: "en",
      backdrop_path: "/acfB2tLw0F2NUwvY1XQoCaNTRgR.jpg",
      overview:
        "Follow a teenage girl and a trio of fallen gods on a perilous journey as they attempt to bring an end to a demonic reign of chaos and restore balance to their world. Inspired by the 16th Century Chinese fable “Journey to the West.”",
      origin_country: ["NZ"],
      popularity: 35.269,
      media_type: "tv",
    },
    {
      original_name: "Alta mar",
      id: 88239,
      name: "High Seas",
      vote_count: 35,
      vote_average: 6.6,
      first_air_date: "2019-05-24",
      poster_path: "/lzrnCDxQDvciVPWH9idxKRNaLKk.jpg",
      genre_ids: [80, 18],
      original_language: "es",
      backdrop_path: "/vSgn4IeZMiUE7mOgcNaTexPDwcX.jpg",
      overview:
        "Two sisters discover disturbing family secrets after a string of mysterious deaths occur on a luxury ship traveling from Spain to Brazil in the 1940s.",
      origin_country: ["ES"],
      popularity: 70.209,
      media_type: "tv",
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
